# Generated by Django 6.0.2 on 2026-02-09 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(default='2023-2024', max_length=20)),
                ('subject', models.CharField(default='PDSM', max_length=100)),
                ('s_no', models.IntegerField()),
                ('regd_no', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('m1q1a', models.FloatField(blank=True, default=0, null=True)),
                ('m1q1b', models.FloatField(blank=True, default=0, null=True)),
                ('m1q2a', models.FloatField(blank=True, default=0, null=True)),
                ('m1q2b', models.FloatField(blank=True, default=0, null=True)),
                ('m1q3a', models.FloatField(blank=True, default=0, null=True)),
                ('m1q3b', models.FloatField(blank=True, default=0, null=True)),
                ('m1qu1', models.FloatField(blank=True, default=0, null=True)),
                ('m1a1', models.FloatField(blank=True, default=0, null=True)),
                ('m2q1a', models.FloatField(blank=True, default=0, null=True)),
                ('m2q1b', models.FloatField(blank=True, default=0, null=True)),
                ('m2q2a', models.FloatField(blank=True, default=0, null=True)),
                ('m2q2b', models.FloatField(blank=True, default=0, null=True)),
                ('m2q3a', models.FloatField(blank=True, default=0, null=True)),
                ('m2q3b', models.FloatField(blank=True, default=0, null=True)),
                ('m2qu2', models.FloatField(blank=True, default=0, null=True)),
                ('m2a2', models.FloatField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'student_marks',
                'ordering': ['s_no'],
            },
        ),
    ]
