# Generated by Django 6.0.2 on 2026-02-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='academic_year',
        ),
        migrations.RemoveField(
            model_name='studentmarks',
            name='subject',
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='batch',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='semester',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='studentmarks',
            name='subject_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
