# Generated by Django 6.0.2 on 2026-02-09 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_studentmarks_academic_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmarks',
            name='name',
        ),
    ]
